CREATE TABLE book (
	id SERIAL PRIMARY KEY,
	isbn VARCHAR(30) NOT NULL UNIQUE,
	title VARCHAR(100) NOT NULL,
	notes TEXT NOT NULL,
	author VARCHAR (45),
	date DATE NOT NULL,
	rating SMALLINT NOT NULL
);

INSERT INTO book (isbn, title, notes, author, date, rating)
VALUES ('978-1878424310', 'The Four Agreements: A Practical Guide to Personal Freedom', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam. Pellentesque nec nam aliquam sem et tortor consequat. Non odio euismod lacinia at quis risus sed. Eget sit amet tellus cras. At imperdiet dui accumsan sit. Ornare massa eget egestas purus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit. Augue lacus viverra vitae congue eu consequat. Pellentesque sit amet porttitor eget dolor morbi non. Vitae auctor eu augue ut lectus arcu bibendum at varius. Aliquet risus feugiat in ante metus dictum. Ultricies mi quis hendrerit dolor magna eget. Ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl.', 'Don Miguel Ruiz', '1997-11-01', 9);

INSERT INTO book (isbn, title, notes, author, date, rating)
VALUES ('978-1585424337', 'Think and Grow Rich', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam. Pellentesque nec nam aliquam sem et tortor consequat. Non odio euismod lacinia at quis risus sed. Eget sit amet tellus cras. At imperdiet dui accumsan sit. Ornare massa eget egestas purus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit. Augue lacus viverra vitae congue eu consequat. Pellentesque sit amet porttitor eget dolor morbi non. Vitae auctor eu augue ut lectus arcu bibendum at varius. Aliquet risus feugiat in ante metus dictum. Ultricies mi quis hendrerit dolor magna eget. Ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl.', 'Napoleon Hill', '2007-12-15', 10);

INSERT INTO book (isbn, title, notes, author, date, rating)
VALUES('978-0140280197', 'The 48 Laws of Power', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam. Pellentesque nec nam aliquam sem et tortor consequat. Non odio euismod lacinia at quis risus sed. Eget sit amet tellus cras. At imperdiet dui accumsan sit. Ornare massa eget egestas purus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit. Augue lacus viverra vitae congue eu consequat. Pellentesque sit amet porttitor eget dolor morbi non. Vitae auctor eu augue ut lectus arcu bibendum at varius. Aliquet risus feugiat in ante metus dictum. Ultricies mi quis hendrerit dolor magna eget. Ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl.', 'Robert Greene', '2000-09-01', 9);

INSERT INTO book (isbn, title, notes, author, date, rating)
VALUES ('978-1-5247-6316-9', 'A Promised Land', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam. Pellentesque nec nam aliquam sem et tortor consequat. Non odio euismod lacinia at quis risus sed. Eget sit amet tellus cras. At imperdiet dui accumsan sit. Ornare massa eget egestas purus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit. Augue lacus viverra vitae congue eu consequat. Pellentesque sit amet porttitor eget dolor morbi non. Vitae auctor eu augue ut lectus arcu bibendum at varius. Aliquet risus feugiat in ante metus dictum. Ultricies mi quis hendrerit dolor magna eget. Ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl.', 'Barack Obama', '2020-11-17', 10);

INSERT INTO book (isbn, title, notes, author, date, rating)
VALUES ('9781838856281', 'Cacophony of Bone', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam. Pellentesque nec nam aliquam sem et tortor consequat. Non odio euismod lacinia at quis risus sed. Eget sit amet tellus cras. At imperdiet dui accumsan sit. Ornare massa eget egestas purus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit. Augue lacus viverra vitae congue eu consequat. Pellentesque sit amet porttitor eget dolor morbi non. Vitae auctor eu augue ut lectus arcu bibendum at varius. Aliquet risus feugiat in ante metus dictum. Ultricies mi quis hendrerit dolor magna eget. Ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl. ', 'Kerri ní Dochartaigh', '2023-11-14', 8);

INSERT INTO book (isbn, title, notes, author, date, rating)
VALUES ('9780307377906', 'The Righteous Mind: Why Good People Are Divided by Politics and Religion', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam. Pellentesque nec nam aliquam sem et tortor consequat. Non odio euismod lacinia at quis risus sed. Eget sit amet tellus cras. At imperdiet dui accumsan sit. Ornare massa eget egestas purus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit. Augue lacus viverra vitae congue eu consequat. Pellentesque sit amet porttitor eget dolor morbi non. Vitae auctor eu augue ut lectus arcu bibendum at varius. Aliquet risus feugiat in ante metus dictum. Ultricies mi quis hendrerit dolor magna eget. Ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl.', 'Jonathan Haidt', '2012-03-13', 8);

INSERT INTO book (isbn, title, notes, author, date, rating)
VALUES ('9781611803006', 'The Religion of Tomorrow', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam. Pellentesque nec nam aliquam sem et tortor consequat. Non odio euismod lacinia at quis risus sed. Eget sit amet tellus cras. At imperdiet dui accumsan sit. Ornare massa eget egestas purus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit. Augue lacus viverra vitae congue eu consequat. Pellentesque sit amet porttitor eget dolor morbi non. Vitae auctor eu augue ut lectus arcu bibendum at varius. Aliquet risus feugiat in ante metus dictum. Ultricies mi quis hendrerit dolor magna eget. Ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl.', 'Ken Wilber', '2017-05-02', 8);

INSERT INTO book (isbn, title, notes, author, date, rating)
VALUES ('9780307352149', 'Quiet: The Power of Introverts in a World That Can t Stop Talking', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam. Pellentesque nec nam aliquam sem et tortor consequat. Non odio euismod lacinia at quis risus sed. Eget sit amet tellus cras. At imperdiet dui accumsan sit. Ornare massa eget egestas purus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit. Augue lacus viverra vitae congue eu consequat. Pellentesque sit amet porttitor eget dolor morbi non. Vitae auctor eu augue ut lectus arcu bibendum at varius. Aliquet risus feugiat in ante metus dictum. Ultricies mi quis hendrerit dolor magna eget. Ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl. ', 'Susan Cain', '2012-01-24', 8);

INSERT INTO book (isbn, title, notes, author, date, rating)
VALUES ('9780374275631', 'Thinking, Fast and Slow', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam. Pellentesque nec nam aliquam sem et tortor consequat. Non odio euismod lacinia at quis risus sed. Eget sit amet tellus cras. At imperdiet dui accumsan sit. Ornare massa eget egestas purus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit. Augue lacus viverra vitae congue eu consequat. Pellentesque sit amet porttitor eget dolor morbi non. Vitae auctor eu augue ut lectus arcu bibendum at varius. Aliquet risus feugiat in ante metus dictum. Ultricies mi quis hendrerit dolor magna eget. Ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl.', 'Daniel Kahneman', '2011-10-25', 8);

INSERT INTO book (isbn, title, notes, author, date, rating)
VALUES ('9781982120306', 'Truth Be Told: My Journey Through Life and the Law', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam. Pellentesque nec nam aliquam sem et tortor consequat. Non odio euismod lacinia at quis risus sed. Eget sit amet tellus cras. At imperdiet dui accumsan sit. Ornare massa eget egestas purus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit. Augue lacus viverra vitae congue eu consequat. Pellentesque sit amet porttitor eget dolor morbi non. Vitae auctor eu augue ut lectus arcu bibendum at varius. Aliquet risus feugiat in ante metus dictum. Ultricies mi quis hendrerit dolor magna eget. Ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl.', 'Beverley McLachlin', '2019-09-24', 8);

INSERT INTO book (isbn, title, notes, author, date, rating)
VALUES ('9781627792127', 'Six of Crows', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam. Pellentesque nec nam aliquam sem et tortor consequat. Non odio euismod lacinia at quis risus sed. Eget sit amet tellus cras. At imperdiet dui accumsan sit. Ornare massa eget egestas purus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit. Augue lacus viverra vitae congue eu consequat. Pellentesque sit amet porttitor eget dolor morbi non. Vitae auctor eu augue ut lectus arcu bibendum at varius. Aliquet risus feugiat in ante metus dictum. Ultricies mi quis hendrerit dolor magna eget. Ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl. ', 'Leigh Bardugo', '2023-01-01', 8);

INSERT INTO book (isbn, title, notes, author, date, rating)
VALUES ('978-1936891023', 'The War of Art: Break Through the Blocks and Win Your Inner Creative Battles', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam. Pellentesque nec nam aliquam sem et tortor consequat. Non odio euismod lacinia at quis risus sed. Eget sit amet tellus cras. At imperdiet dui accumsan sit. Ornare massa eget egestas purus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit. Augue lacus viverra vitae congue eu consequat. Pellentesque sit amet porttitor eget dolor morbi non. Vitae auctor eu augue ut lectus arcu bibendum at varius. Aliquet risus feugiat in ante metus dictum. Ultricies mi quis hendrerit dolor magna eget. Ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl. ', 'Steven Pressfield', '2012-01-11', 9);

INSERT INTO book (isbn, title, notes, author, date, rating)
VALUES ('978-8184959451', 'A Million Thoughts: Learn All About Meditation from a Himalayan Mystic', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam. Pellentesque nec nam aliquam sem et tortor consequat. Non odio euismod lacinia at quis risus sed. Eget sit amet tellus cras. At imperdiet dui accumsan sit. Ornare massa eget egestas purus. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit. Augue lacus viverra vitae congue eu consequat. Pellentesque sit amet porttitor eget dolor morbi non. Vitae auctor eu augue ut lectus arcu bibendum at varius. Aliquet risus feugiat in ante metus dictum. Ultricies mi quis hendrerit dolor magna eget. Ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl. ', 'Om Swami', '2016-11-16', 9);